# This is a basic workflow to help you get started with Actions

name: SIL Tests

on:
  push:
  pull_request:

jobs:      
  sil-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install build toolchain
      run: sudo apt-get install gcc-arm-none-eabi
    
    - name: Build
      working-directory: Debug
      run: make all -j2

    - name: Run test battery
      working-directory: validation
      run: docker-compose up
      
    - name: Archive test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{github.sha}}-test-results
        path: validation/results
        
    - name: Upload results to S3 bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        SOURCE_DIR: ./validation/results
        DEST_DIR: ${{github.sha}}
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    - name: Send Slack notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: firmware-validation
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: ${{ secrets.ARTIFACT_ROOT_URL }}/${{github.sha}}/report.html
        SLACK_TITLE: Test Report URL
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
